//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDB_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Field()
        {
            this.LogEntries = new HashSet<LogEntry>();
        }
    
        public int FieldID { get; set; }
        public string CallSign { get; set; }
        public string ACType { get; set; }
        public string FlightRule { get; set; }
        public string Depart { get; set; }
        public string Arrive { get; set; }
        public string Alternate { get; set; }
        public string CruiseAtl { get; set; }
        public string Scratch { get; set; }
        public string Squawk { get; set; }
        public string Route { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogEntry> LogEntries { get; set; }
    }
}
