//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VatSim_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public int Id { get; set; }
        public string IATA_ID { get; set; }
        public string ICAO_ID { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public bool SidRequired { get; set; }
        public bool HasDeparturePlan { get; set; }
        public bool IsConfigured { get; set; }
    }
}
