//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VatSim_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportSid_Restrictions
    {
        public int Id { get; set; }
        public string Airport_ICAO_Id { get; set; }
        public string SID_Id { get; set; }
        public string EngineType { get; set; }
        public Nullable<int> Max_Cruise_Alt { get; set; }
        public Nullable<int> Min_Cruise_Alt { get; set; }
        public string RNAV_Only { get; set; }
        public string SID_Name { get; set; }
    }
}
