//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VatSim_EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VatSimEntities : DbContext
    {
        public VatSimEntities()
            : base("name=VatSimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aircraft> Aircraft { get; set; }
        public DbSet<Airport> Airports { get; set; }
        public DbSet<AirportSid_Restrictions> AirportSid_Restrictions { get; set; }
        public DbSet<CallSign> CallSigns { get; set; }
        public DbSet<DeparturePlan> DeparturePlans { get; set; }
    }
}
