//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ATC_Helper.WebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ATC_HelperDataSoap", Namespace="http://tempuri.org/")]
    public partial class ATC_HelperData : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAirportDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAircraftDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSidRestrictionDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeparturePlanDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCallSignsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ATC_HelperData() {
            this.Url = global::ATC_Helper.Properties.Settings.Default.ATC_Helper_WebService_ATC_HelperData;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAirportDataCompletedEventHandler GetAirportDataCompleted;
        
        /// <remarks/>
        public event GetAircraftDataCompletedEventHandler GetAircraftDataCompleted;
        
        /// <remarks/>
        public event GetSidRestrictionDataCompletedEventHandler GetSidRestrictionDataCompleted;
        
        /// <remarks/>
        public event GetDeparturePlanDataCompletedEventHandler GetDeparturePlanDataCompleted;
        
        /// <remarks/>
        public event GetCallSignsCompletedEventHandler GetCallSignsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAirportData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Airport[] GetAirportData() {
            object[] results = this.Invoke("GetAirportData", new object[0]);
            return ((Airport[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAirportDataAsync() {
            this.GetAirportDataAsync(null);
        }
        
        /// <remarks/>
        public void GetAirportDataAsync(object userState) {
            if ((this.GetAirportDataOperationCompleted == null)) {
                this.GetAirportDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAirportDataOperationCompleted);
            }
            this.InvokeAsync("GetAirportData", new object[0], this.GetAirportDataOperationCompleted, userState);
        }
        
        private void OnGetAirportDataOperationCompleted(object arg) {
            if ((this.GetAirportDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAirportDataCompleted(this, new GetAirportDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAircraftData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Aircraft[] GetAircraftData() {
            object[] results = this.Invoke("GetAircraftData", new object[0]);
            return ((Aircraft[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAircraftDataAsync() {
            this.GetAircraftDataAsync(null);
        }
        
        /// <remarks/>
        public void GetAircraftDataAsync(object userState) {
            if ((this.GetAircraftDataOperationCompleted == null)) {
                this.GetAircraftDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAircraftDataOperationCompleted);
            }
            this.InvokeAsync("GetAircraftData", new object[0], this.GetAircraftDataOperationCompleted, userState);
        }
        
        private void OnGetAircraftDataOperationCompleted(object arg) {
            if ((this.GetAircraftDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAircraftDataCompleted(this, new GetAircraftDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSidRestrictionData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AirportSid_Restrictions[] GetSidRestrictionData() {
            object[] results = this.Invoke("GetSidRestrictionData", new object[0]);
            return ((AirportSid_Restrictions[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSidRestrictionDataAsync() {
            this.GetSidRestrictionDataAsync(null);
        }
        
        /// <remarks/>
        public void GetSidRestrictionDataAsync(object userState) {
            if ((this.GetSidRestrictionDataOperationCompleted == null)) {
                this.GetSidRestrictionDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSidRestrictionDataOperationCompleted);
            }
            this.InvokeAsync("GetSidRestrictionData", new object[0], this.GetSidRestrictionDataOperationCompleted, userState);
        }
        
        private void OnGetSidRestrictionDataOperationCompleted(object arg) {
            if ((this.GetSidRestrictionDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSidRestrictionDataCompleted(this, new GetSidRestrictionDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeparturePlanData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeparturePlan[] GetDeparturePlanData() {
            object[] results = this.Invoke("GetDeparturePlanData", new object[0]);
            return ((DeparturePlan[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDeparturePlanDataAsync() {
            this.GetDeparturePlanDataAsync(null);
        }
        
        /// <remarks/>
        public void GetDeparturePlanDataAsync(object userState) {
            if ((this.GetDeparturePlanDataOperationCompleted == null)) {
                this.GetDeparturePlanDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeparturePlanDataOperationCompleted);
            }
            this.InvokeAsync("GetDeparturePlanData", new object[0], this.GetDeparturePlanDataOperationCompleted, userState);
        }
        
        private void OnGetDeparturePlanDataOperationCompleted(object arg) {
            if ((this.GetDeparturePlanDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeparturePlanDataCompleted(this, new GetDeparturePlanDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCallSigns", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CallSign[] GetCallSigns() {
            object[] results = this.Invoke("GetCallSigns", new object[0]);
            return ((CallSign[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCallSignsAsync() {
            this.GetCallSignsAsync(null);
        }
        
        /// <remarks/>
        public void GetCallSignsAsync(object userState) {
            if ((this.GetCallSignsOperationCompleted == null)) {
                this.GetCallSignsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCallSignsOperationCompleted);
            }
            this.InvokeAsync("GetCallSigns", new object[0], this.GetCallSignsOperationCompleted, userState);
        }
        
        private void OnGetCallSignsOperationCompleted(object arg) {
            if ((this.GetCallSignsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCallSignsCompleted(this, new GetCallSignsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Airport {
        
        private int idField;
        
        private string iATA_IDField;
        
        private string iCAO_IDField;
        
        private string locationField;
        
        private string nameField;
        
        private string countryField;
        
        private bool sidRequiredField;
        
        private bool hasDeparturePlanField;
        
        private bool isConfiguredField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string IATA_ID {
            get {
                return this.iATA_IDField;
            }
            set {
                this.iATA_IDField = value;
            }
        }
        
        /// <remarks/>
        public string ICAO_ID {
            get {
                return this.iCAO_IDField;
            }
            set {
                this.iCAO_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public bool SidRequired {
            get {
                return this.sidRequiredField;
            }
            set {
                this.sidRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool HasDeparturePlan {
            get {
                return this.hasDeparturePlanField;
            }
            set {
                this.hasDeparturePlanField = value;
            }
        }
        
        /// <remarks/>
        public bool IsConfigured {
            get {
                return this.isConfiguredField;
            }
            set {
                this.isConfiguredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CallSign {
        
        private int idField;
        
        private string airlineIDField;
        
        private string callSign1Field;
        
        private string companyField;
        
        private string countryField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string AirlineID {
            get {
                return this.airlineIDField;
            }
            set {
                this.airlineIDField = value;
            }
        }
        
        /// <remarks/>
        public string CallSign1 {
            get {
                return this.callSign1Field;
            }
            set {
                this.callSign1Field = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeparturePlan {
        
        private int idField;
        
        private string iCAO_IDField;
        
        private string flightRulesField;
        
        private string sID_IDField;
        
        private string transition_IDField;
        
        private string directionOfFlightField;
        
        private string runwayField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ICAO_ID {
            get {
                return this.iCAO_IDField;
            }
            set {
                this.iCAO_IDField = value;
            }
        }
        
        /// <remarks/>
        public string FlightRules {
            get {
                return this.flightRulesField;
            }
            set {
                this.flightRulesField = value;
            }
        }
        
        /// <remarks/>
        public string SID_ID {
            get {
                return this.sID_IDField;
            }
            set {
                this.sID_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Transition_ID {
            get {
                return this.transition_IDField;
            }
            set {
                this.transition_IDField = value;
            }
        }
        
        /// <remarks/>
        public string DirectionOfFlight {
            get {
                return this.directionOfFlightField;
            }
            set {
                this.directionOfFlightField = value;
            }
        }
        
        /// <remarks/>
        public string Runway {
            get {
                return this.runwayField;
            }
            set {
                this.runwayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AirportSid_Restrictions {
        
        private int idField;
        
        private string airport_ICAO_IdField;
        
        private string sID_IdField;
        
        private string engineTypeField;
        
        private System.Nullable<int> max_Cruise_AltField;
        
        private System.Nullable<int> min_Cruise_AltField;
        
        private string rNAV_OnlyField;
        
        private string sID_NameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Airport_ICAO_Id {
            get {
                return this.airport_ICAO_IdField;
            }
            set {
                this.airport_ICAO_IdField = value;
            }
        }
        
        /// <remarks/>
        public string SID_Id {
            get {
                return this.sID_IdField;
            }
            set {
                this.sID_IdField = value;
            }
        }
        
        /// <remarks/>
        public string EngineType {
            get {
                return this.engineTypeField;
            }
            set {
                this.engineTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Max_Cruise_Alt {
            get {
                return this.max_Cruise_AltField;
            }
            set {
                this.max_Cruise_AltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Min_Cruise_Alt {
            get {
                return this.min_Cruise_AltField;
            }
            set {
                this.min_Cruise_AltField = value;
            }
        }
        
        /// <remarks/>
        public string RNAV_Only {
            get {
                return this.rNAV_OnlyField;
            }
            set {
                this.rNAV_OnlyField = value;
            }
        }
        
        /// <remarks/>
        public string SID_Name {
            get {
                return this.sID_NameField;
            }
            set {
                this.sID_NameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Aircraft {
        
        private int idField;
        
        private string manufacturerField;
        
        private string modelField;
        
        private string typeDesignatorField;
        
        private string descriptionField;
        
        private string engineTypeField;
        
        private string simplifiedEngineTypeField;
        
        private System.Nullable<int> engineCountField;
        
        private string wTCField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string TypeDesignator {
            get {
                return this.typeDesignatorField;
            }
            set {
                this.typeDesignatorField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string EngineType {
            get {
                return this.engineTypeField;
            }
            set {
                this.engineTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SimplifiedEngineType {
            get {
                return this.simplifiedEngineTypeField;
            }
            set {
                this.simplifiedEngineTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> EngineCount {
            get {
                return this.engineCountField;
            }
            set {
                this.engineCountField = value;
            }
        }
        
        /// <remarks/>
        public string WTC {
            get {
                return this.wTCField;
            }
            set {
                this.wTCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetAirportDataCompletedEventHandler(object sender, GetAirportDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAirportDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAirportDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Airport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Airport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetAircraftDataCompletedEventHandler(object sender, GetAircraftDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAircraftDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAircraftDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Aircraft[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Aircraft[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetSidRestrictionDataCompletedEventHandler(object sender, GetSidRestrictionDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSidRestrictionDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSidRestrictionDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AirportSid_Restrictions[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AirportSid_Restrictions[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetDeparturePlanDataCompletedEventHandler(object sender, GetDeparturePlanDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeparturePlanDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeparturePlanDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeparturePlan[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeparturePlan[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetCallSignsCompletedEventHandler(object sender, GetCallSignsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCallSignsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCallSignsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CallSign[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CallSign[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591