//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATC_Helper_EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtcHelperEntities : DbContext
    {
        public AtcHelperEntities()
            : base("name=AtcHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<AirportSid_Restrictions> AirportSid_Restrictions { get; set; }
        public virtual DbSet<CallSign> CallSigns { get; set; }
        public virtual DbSet<DeparturePlan> DeparturePlans { get; set; }
    }
}
