//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATC_Helper_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallSign
    {
        public int Id { get; set; }
        public string AirlineID { get; set; }
        public string CallSign1 { get; set; }
        public string Company { get; set; }
        public string Country { get; set; }
    }
}
