//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATC_Helper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".pdcclt")]
        public string Pdc {
            get {
                return ((string)(this["Pdc"]));
            }
            set {
                this["Pdc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".pdccltd")]
        public string PdcNoDep {
            get {
                return ((string)(this["PdcNoDep"]));
            }
            set {
                this["PdcNoDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".pdccltme")]
        public string PdcMe {
            get {
                return ((string)(this["PdcMe"]));
            }
            set {
                this["PdcMe"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://chrisgonzalez.net/WS/Logging.asmx")]
        public string ATC_Helper_chrisgonzalez_Logging {
            get {
                return ((string)(this["ATC_Helper_chrisgonzalez_Logging"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://chrisgonzalez.net/WS/ATC-HelperData.asmx")]
        public string ATC_Helper_WebService_ATC_HelperData {
            get {
                return ((string)(this["ATC_Helper_WebService_ATC_HelperData"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Collapse_AirportDetails {
            get {
                return ((bool)(this["Collapse_AirportDetails"]));
            }
            set {
                this["Collapse_AirportDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Collapse_FlightplanDetails {
            get {
                return ((bool)(this["Collapse_FlightplanDetails"]));
            }
            set {
                this["Collapse_FlightplanDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Collapse_ClearanceDetails {
            get {
                return ((bool)(this["Collapse_ClearanceDetails"]));
            }
            set {
                this["Collapse_ClearanceDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Collapse_PDCCommands {
            get {
                return ((bool)(this["Collapse_PDCCommands"]));
            }
            set {
                this["Collapse_PDCCommands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RememberWindowsSettings {
            get {
                return ((bool)(this["RememberWindowsSettings"]));
            }
            set {
                this["RememberWindowsSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmMainPosition {
            get {
                return ((global::System.Drawing.Point)(this["frmMainPosition"]));
            }
            set {
                this["frmMainPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmSettingsPosition {
            get {
                return ((global::System.Drawing.Point)(this["frmSettingsPosition"]));
            }
            set {
                this["frmSettingsPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmAircraftPosition {
            get {
                return ((global::System.Drawing.Point)(this["frmAircraftPosition"]));
            }
            set {
                this["frmAircraftPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmAirportPosition {
            get {
                return ((global::System.Drawing.Point)(this["frmAirportPosition"]));
            }
            set {
                this["frmAirportPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmCallsignPosition {
            get {
                return ((global::System.Drawing.Point)(this["frmCallsignPosition"]));
            }
            set {
                this["frmCallsignPosition"] = value;
            }
        }
    }
}
