//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ATC_Helper.chrisgonzalez {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoggingSoap", Namespace="http://tempuri.org/")]
    public partial class Logging : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LogErrorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Logging() {
            this.Url = global::ATC_Helper.Properties.Settings.Default.ATC_Helper_chrisgonzalez_Logging;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LogErrorCompletedEventHandler LogErrorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LogError(string method, string application, string exception, string stackTrace, Fields fields) {
            object[] results = this.Invoke("LogError", new object[] {
                        method,
                        application,
                        exception,
                        stackTrace,
                        fields});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LogErrorAsync(string method, string application, string exception, string stackTrace, Fields fields) {
            this.LogErrorAsync(method, application, exception, stackTrace, fields, null);
        }
        
        /// <remarks/>
        public void LogErrorAsync(string method, string application, string exception, string stackTrace, Fields fields, object userState) {
            if ((this.LogErrorOperationCompleted == null)) {
                this.LogErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogErrorOperationCompleted);
            }
            this.InvokeAsync("LogError", new object[] {
                        method,
                        application,
                        exception,
                        stackTrace,
                        fields}, this.LogErrorOperationCompleted, userState);
        }
        
        private void OnLogErrorOperationCompleted(object arg) {
            if ((this.LogErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogErrorCompleted(this, new LogErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Fields {
        
        private string callSignField;
        
        private string acTypeField;
        
        private string flightRulesField;
        
        private string departureAirportField;
        
        private string arrivalAirportField;
        
        private string alternateAirportField;
        
        private string cruiseAltitudeField;
        
        private string scratchPadField;
        
        private string squwakField;
        
        private string routeField;
        
        private string remarksField;
        
        /// <remarks/>
        public string CallSign {
            get {
                return this.callSignField;
            }
            set {
                this.callSignField = value;
            }
        }
        
        /// <remarks/>
        public string AcType {
            get {
                return this.acTypeField;
            }
            set {
                this.acTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FlightRules {
            get {
                return this.flightRulesField;
            }
            set {
                this.flightRulesField = value;
            }
        }
        
        /// <remarks/>
        public string DepartureAirport {
            get {
                return this.departureAirportField;
            }
            set {
                this.departureAirportField = value;
            }
        }
        
        /// <remarks/>
        public string ArrivalAirport {
            get {
                return this.arrivalAirportField;
            }
            set {
                this.arrivalAirportField = value;
            }
        }
        
        /// <remarks/>
        public string AlternateAirport {
            get {
                return this.alternateAirportField;
            }
            set {
                this.alternateAirportField = value;
            }
        }
        
        /// <remarks/>
        public string CruiseAltitude {
            get {
                return this.cruiseAltitudeField;
            }
            set {
                this.cruiseAltitudeField = value;
            }
        }
        
        /// <remarks/>
        public string ScratchPad {
            get {
                return this.scratchPadField;
            }
            set {
                this.scratchPadField = value;
            }
        }
        
        /// <remarks/>
        public string Squwak {
            get {
                return this.squwakField;
            }
            set {
                this.squwakField = value;
            }
        }
        
        /// <remarks/>
        public string Route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void LogErrorCompletedEventHandler(object sender, LogErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591