// Decompiled with JetBrains decompiler
// Type: FpAssistantCore.Icao.ICAOLocationIndicators
// Assembly: FpAssistantCoreScl, Version=2021.10.8.1, Culture=neutral, PublicKeyToken=1928072adf1fc70c
// MVID: ED7682A4-0062-40BE-BD58-F87033EB2068
// Assembly location: C:\Users\Me\OneDrive\Documents\Visual Studio 2022\Projects\CLT Clearence\CLT Clearence\bin\Debug\FpAssistantCoreScl.dll

using FpAssistantCore.General;

namespace FpAssistantCore.Icao
{
  public enum ICAOLocationIndicators
  {
    [Description(Text = "Afghanistan")] OA,
    [Description(Text = "Albania")] PA,
    [Description(Text = "Albania")] LA,
    [Description(Text = "Algeria")] DA,
    [Description(Text = "American Samoa")] NS,
    [Description(Text = "Angola")] FN,
    [Description(Text = "Anguilla")] TQ,
    [Description(Text = "Antigua and Barbuda")] TA,
    [Description(Text = "Argentina")] SA,
    [Description(Text = "Armenia and Georgia")] UG,
    [Description(Text = "Aruba / Netherlands Antilles")] TN,
    [Description(Text = "Ascension Islands")] FH,
    [Description(Text = "Australia")] YB,
    [Description(Text = "Australia")] YM,
    [Description(Text = "Austria")] LO,
    [Description(Text = "Azerbiajan")] UB,
    [Description(Text = "Bahamas")] MY,
    [Description(Text = "Bahrain")] OB,
    [Description(Text = "Bangladesh")] VG,
    [Description(Text = "Barbados")] TB,
    [Description(Text = "Belarus, Latvia and Lithuania")] UM,
    [Description(Text = "Belgium")] EB,
    [Description(Text = "Belize")] MZ,
    [Description(Text = "Benin")] DB,
    [Description(Text = "Bermuda")] TX,
    [Description(Text = "Bolivia")] SL,
    [Description(Text = "Bosnia and Herzegovinia")] LQ,
    [Description(Text = "Botswana")] FB,
    [Description(Text = "Brazil")] SB,
    [Description(Text = "Brunei")] WB,
    [Description(Text = "Bulgaria")] LB,
    [Description(Text = "Burkina Faso")] DF,
    [Description(Text = "Burundi")] HB,
    [Description(Text = "Cambodia")] VD,
    [Description(Text = "Cameroon")] FK,
    [Description(Text = "Canada")] CY,
    [Description(Text = "Canary Islands")] GC,
    [Description(Text = "Chad")] FT,
    [Description(Text = "Chile")] SC,
    [Description(Text = "China")] ZB,
    [Description(Text = "China")] ZG,
    [Description(Text = "China")] ZH,
    [Description(Text = "China")] ZL,
    [Description(Text = "China")] ZP,
    [Description(Text = "China")] ZS,
    [Description(Text = "China")] ZU,
    [Description(Text = "China")] ZW,
    [Description(Text = "China")] ZY,
    [Description(Text = "Colombia")] SK,
    [Description(Text = "Congo")] FC,
    [Description(Text = "Cook Islands")] NC,
    [Description(Text = "Costa Rica")] MR,
    [Description(Text = "Croatia")] LD,
    [Description(Text = "Cuba")] MU,
    [Description(Text = "Cyprus")] LC,
    [Description(Text = "Czech Republic")] LK,
    [Description(Text = "Democratic Republic of Congo")] FZ,
    [Description(Text = "Denmark")] EK,
    [Description(Text = "Diego Garcia")] FJ,
    [Description(Text = "Djibouti")] HD,
    [Description(Text = "Dominica")] TD,
    [Description(Text = "Dominican Republic")] MD,
    [Description(Text = "Egypt")] HE,
    [Description(Text = "El Salvador")] MS,
    [Description(Text = "Equador")] SE,
    [Description(Text = "Equatorial Guinea")] FG,
    [Description(Text = "Eritrea")] HH,
    [Description(Text = "Estonia")] EE,
    [Description(Text = "Ethiopia")] HA,
    [Description(Text = "Fiji")] NF,
    [Description(Text = "Finland")] EF,
    [Description(Text = "France")] LF,
    [Description(Text = "French Antilles")] TF,
    [Description(Text = "French Guyana")] SO,
    [Description(Text = "Gabon")] FO,
    [Description(Text = "Gambia")] GB,
    [Description(Text = "Germany - Civil")] ED,
    [Description(Text = "Germany - Military")] ET,
    [Description(Text = "Ghana")] DG,
    [Description(Text = "Gibralter")] LX,
    [Description(Text = "Greece")] LG,
    [Description(Text = "Greenland")] BG,
    [Description(Text = "Grenada")] TG,
    [Description(Text = "Guam")] PG,
    [Description(Text = "Guatemala")] MG,
    [Description(Text = "Guinea")] GU,
    [Description(Text = "Guinea Bissau")] GG,
    [Description(Text = "Guyana")] SY,
    [Description(Text = "Haiti")] MT,
    [Description(Text = "Hawaii")] PH,
    [Description(Text = "Honduras")] MH,
    [Description(Text = "Hong Kong")] VH,
    [Description(Text = "Hungary")] LH,
    [Description(Text = "Iceland")] BI,
    [Description(Text = "India - East")] VE,
    [Description(Text = "India - North")] VI,
    [Description(Text = "India - South")] VO,
    [Description(Text = "India - West")] VA,
    [Description(Text = "Indonesia")] WA,
    [Description(Text = "Indonesia")] WI,
    [Description(Text = "Indonesia - Bali")] WR,
    [Description(Text = "Iran")] OI,
    [Description(Text = "Iraq")] OR,
    [Description(Text = "Ireland")] EI,
    [Description(Text = "Israel")] LL,
    [Description(Text = "Italy")] LI,
    [Description(Text = "Ivory Coast")] DI,
    [Description(Text = "Jamaica")] MK,
    [Description(Text = "Japan")] RJ,
    [Description(Text = "Johnston Islands")] PJ,
    [Description(Text = "Jordan")] OJ,
    [Description(Text = "Kazakhstan and Kyrgyzstan")] UA,
    [Description(Text = "Kenya")] HK,
    [Description(Text = "Kiribati Islands")] NG,
    [Description(Text = "Korea")] RK,
    [Description(Text = "Kuwait")] OK,
    [Description(Text = "Laos")] VL,
    [Description(Text = "Latvia")] EV,
    [Description(Text = "Lebanon")] OL,
    [Description(Text = "Lesotho")] FX,
    [Description(Text = "Liberia")] GL,
    [Description(Text = "Libya")] HL,
    [Description(Text = "Line Islands")] PL,
    [Description(Text = "Lithuania")] EY,
    [Description(Text = "Luxembourg")] EL,
  }
}
